spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: bandar@gmail.com
    password: 16-charater 
    properties:      mail:
        smtp:
          auth: true
          starttls:
           enable: true